name: Build 
 
on:
  push:
    branches:
      - dwiza

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Composer dependencies
      run: composer install

    - name: Install Node.js dependencies
      run: npm install

    - name: Build TailwindCSS
      run: npx tailwindcss -i ./styles.css -o ./output.css --build

    - name: Run PHP unit tests
      run: ./vendor/bin/phpunit tests

    - name: Merge branch
      run: |
        git config --global user.name "Dwizza"
        git config --global user.email "oussamaerrahili124@gmail.com"
        git switch main
        git merge dwiza

    # - name: Deploy via FTP
    #   uses: SamKirkland/FTP-Deploy-Action@v4
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./
    #     server-dir: /public_html
